name: Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  RUST_BACKTRACE: full
  ACTIONS_RUNNER_DEBUG: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: "ðŸ”‘ Checkout"
        uses: actions/checkout@v6

      - name: "ðŸ¦€ Setup Rust"
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
          targets: wasm32-unknown-unknown

      - name: "Install sccache"
        uses: mozilla-actions/sccache-action@main

      - name: "ðŸ“¦ Cache cargo"
        uses: actions/cache@main
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: "ðŸ¦– Setup Deno"
        uses: denoland/setup-deno@main
        with:
          deno-version: "latest"

      - name: Build & Deploy
        run: |
          deno run \
            --allow-all \
            jsr:@deno/wasmbuild@0.19.2 \
            --project='solarpark' \
            --out='dist'

          sleep 1

          deno deploy \
            --app='solar' \
            --prod \
            --token ${{ secrets.DENO_DEPLOY_TOKEN }}
